version: '1'

networks:
  node_network:
    driver: bridge

services:
  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    networks:
      - node_network

  gpt-node01:
    build: .
    networks:
      - node_network
    deploy:
      restart_policy:
        condition: on-failure

  gpt-node02:
    build: .
    deploy:
      restart_policy:
        condition: on-failure
    networks:
      - node_network

  gpt-node03:
    build: .
    deploy:
      restart_policy:
        condition: on-failure
    networks:
      - node_network

  gpt-node04:
    build: .
    deploy:
      restart_policy:
        condition: on-failure
    networks:
      - node_network

  gpt-node05:
    build: .
    deploy:
      restart_policy:
        condition: on-failure
    networks:
      - node_network